import { readdir, readFile, stat } from "node:fs/promises";
import path from "node:path";

const DIST_DIR = path.resolve(process.cwd(), "frontend", "dist");
const OUTPUT_FILE = path.resolve(process.cwd(), "backend", "embeddedAssets.ts");

async function getAllFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const res = path.resolve(dir, entry.name);
      return entry.isDirectory() ? getAllFiles(res) : res;
    })
  );
  return Array.prototype.concat(...files);
}

async function bundle() {
  console.log("Bundling assets from:", DIST_DIR);
  const files = await getAllFiles(DIST_DIR);
  const assets: Record<string, { content: string; mime: string }> = {};

  for (const file of files) {
    const relativePath = path.relative(DIST_DIR, file).replace(/\\/g, "/");
    const key = "/" + relativePath;
    const content = await readFile(file);
    const ext = path.extname(file).toLowerCase();

    let mime = "application/octet-stream";
    if (ext === ".html") mime = "text/html; charset=utf-8";
    else if (ext === ".js") mime = "text/javascript; charset=utf-8";
    else if (ext === ".css") mime = "text/css; charset=utf-8";
    else if (ext === ".svg") mime = "image/svg+xml";
    else if (ext === ".png") mime = "image/png";
    else if (ext === ".jpg" || ext === ".jpeg") mime = "image/jpeg";
    else if (ext === ".ico") mime = "image/x-icon";

    // Base64 エンコードして埋め込む
    assets[key] = {
      content: content.toString("base64"),
      mime
    };
  }

  const tsContent = `// Auto-generated by bundle-assets.ts
export const EMBEDDED_ASSETS: Record<string, { content: string; mime: string }> = ${JSON.stringify(assets, null, 2)};
`;

  await Bun.write(OUTPUT_FILE, tsContent);
  console.log(`Successfully bundled ${Object.keys(assets).length} assets into ${OUTPUT_FILE}`);
}

bundle().catch(console.error);
